name: Build Frontend and Backend

on:
  push:
    branches:
      - master

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            raniaat12/front:${{ github.sha }}
            raniaat12/front:latest

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            raniaat12/mono-backend:${{ github.sha }}
            raniaat12/mono-backend:latest

  # ─────────────────────────────────────────
  # JOB 3 : Met à jour les manifests dans k8s-project-heat
  # ─────────────────────────────────────────
  update-manifests:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout k8s-project-heat  # ← l'AUTRE repo
        uses: actions/checkout@v4
        with:
          repository: rassaasarra/k8s-project-heat
          token: ${{ secrets.GH_PAT }}   # ← token personnel, pas GITHUB_TOKEN
          ref: main

      - name: Update frontend image tag
        run: |
          sed -i "s|raniaat12/front:.*|raniaat12/front:${{ github.sha }}|g" \
            k8s/frontend-deployment.yaml

      - name: Update backend image tag
        run: |
          sed -i "s|raniaat12/mono-backend:.*|raniaat12/mono-backend:${{ github.sha }}|g" \
            k8s/backend-deployment.yaml

      - name: Commit & Push dans k8s-project-heat
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add k8s/frontend-deployment.yaml k8s/backend-deployment.yaml
          git diff --staged --quiet || git commit -m "ci: update images to ${{ github.sha }}"
          git push
